// <auto-generated />
using System;
using GaidoSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GaidoSystem.Migrations
{
    [DbContext(typeof(GaidoSystemContext))]
    [Migration("20190829040501_DropAnualidad")]
    partial class DropAnualidad
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GaidoSystem.Models.AnualidadER", b =>
                {
                    b.Property<int>("AnualidadERId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Notas")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Year");

                    b.HasKey("AnualidadERId");

                    b.ToTable("AnualidadER");
                });

            modelBuilder.Entity("GaidoSystem.Models.HistorialER", b =>
                {
                    b.Property<int>("HistorialERId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CostosVentas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha");

                    b.Property<decimal>("GastosAdmin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastosOperativos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastosVentas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModeloProyeccionId");

                    b.Property<decimal>("OtrosGastos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Utilidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UtilidadNeta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VentasNetas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistorialERId");

                    b.HasIndex("ModeloProyeccionId");

                    b.ToTable("HistorialER");
                });

            modelBuilder.Entity("GaidoSystem.Models.ModeloProyeccion", b =>
                {
                    b.Property<int>("ModeloProyeccionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha");

                    b.Property<decimal>("ModCostosVentas")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("ModGastosAdmin")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("ModGastosOperativos")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("ModGastosVentas")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("ModOtrosGastos")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("ModVentasNetas")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("ModeloProyeccionId");

                    b.ToTable("ModeloProyeccion");
                });

            modelBuilder.Entity("GaidoSystem.Models.Proyecciones", b =>
                {
                    b.Property<int>("ProyeccionesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("ModeloProyeccionId");

                    b.Property<decimal>("ProCostosVentas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProGastosAdmin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProGastosOperativos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProGastosVentas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProOtrosGastos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProVentasNetas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProyeccionesId");

                    b.HasIndex("ModeloProyeccionId");

                    b.ToTable("Proyecciones");
                });

            modelBuilder.Entity("GaidoSystem.Models.HistorialER", b =>
                {
                    b.HasOne("GaidoSystem.Models.ModeloProyeccion")
                        .WithMany("HistotialesER")
                        .HasForeignKey("ModeloProyeccionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GaidoSystem.Models.Proyecciones", b =>
                {
                    b.HasOne("GaidoSystem.Models.ModeloProyeccion", "ModeloProyeccion")
                        .WithMany("ListaProyecciones")
                        .HasForeignKey("ModeloProyeccionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
